export const makeOptions = [
  { value: "alfa-romeo", label: "ALFA ROMEO", stock: 1 },
  { value: "aston-martin", label: "ASTON MARTIN", stock: 1 },
  { value: "audi", label: "AUDI", stock: 44 },
  { value: "bmw", label: "BMW", stock: 72 },
  { value: "chevrolet", label: "CHEVROLET", stock: 7 },
  { value: "daihatsu", label: "DAIHATSU", stock: 1 },
  { value: "ford", label: "FORD", stock: 9 },
  { value: "honda", label: "HONDA", stock: 18 },
  { value: "toyota", label: "TOYOTA", stock: 24 },
  { value: "nissan", label: "NISSAN", stock: 9 },
  { value: "mercedes", label: "MERCEDES", stock: 5 },
]

export const modelOptions = [
  { value: "camry", label: "CAMRY", stock: 8 },
  { value: "corolla", label: "COROLLA", stock: 6 },
  { value: "civic", label: "CIVIC", stock: 7 },
  { value: "accord", label: "ACCORD", stock: 5 },
  { value: "f150", label: "F-150", stock: 9 },
  { value: "silverado", label: "SILVERADO", stock: 6 },
  { value: "altima", label: "ALTIMA", stock: 4 },
]

export const locationOptions = [
  { value: "seattle", label: "SEATTLE, WA", stock: 42 },
  { value: "portland", label: "PORTLAND, OR", stock: 35 },
  { value: "spokane", label: "SPOKANE, WA", stock: 18 },
  { value: "boise", label: "BOISE, ID", stock: 15 },
  { value: "vancouver", label: "VANCOUVER, WA", stock: 12 },
]

export const yearOptions = [
  { value: "2025", label: "2025", stock: 3 },
  { value: "2024", label: "2024", stock: 15 },
  { value: "2023", label: "2023", stock: 42 },
  { value: "2022", label: "2022", stock: 56 },
  { value: "2021", label: "2021", stock: 38 },
  { value: "2020", label: "2020", stock: 29 },
  { value: "2019", label: "2019", stock: 24 },
  { value: "2018", label: "2018", stock: 18 },
  { value: "2017", label: "2017", stock: 12 },
  { value: "2016", label: "2016", stock: 8 },
]

export const bodyOptions = [
  { value: "suv", label: "SUV", stock: 87 },
  { value: "sedan", label: "SEDAN", stock: 64 },
  { value: "hatchback", label: "HATCHBACK", stock: 32 },
  { value: "coupe", label: "COUPE", stock: 18 },
  { value: "convertible", label: "CONVERTIBLE", stock: 9 },
  { value: "wagon", label: "WAGON", stock: 7 },
  { value: "truck", label: "TRUCK", stock: 15 },
  { value: "van", label: "VAN", stock: 6 },
]

export const priceOptions = [
  { value: "0", label: "$0" },
  { value: "1000", label: "$1,000" },
  { value: "5000", label: "$5,000" },
  { value: "10000", label: "$10,000" },
  { value: "20000", label: "$20,000" },
  { value: "30000", label: "$30,000" },
  { value: "40000", label: "$40,000" },
  { value: "50000", label: "$50,000" },
  { value: "60000", label: "$60,000" },
  { value: "70000", label: "$70,000" },
  { value: "80000", label: "$80,000" },
  { value: "90000", label: "$90,000" },
  { value: "100000", label: "$100,000" },
  { value: "150000", label: "$150,000" },
  { value: "200000", label: "$200,000" },
  { value: "250000", label: "$250,000" },
  { value: "300000", label: "$300,000" },
  { value: "500000", label: "$500,000" },
  { value: "750000", label: "$750,000" },
  { value: "1000000", label: "$1,000,000" },
]

export const dealershipOptions = [
  { value: "all", label: "All Dealerships", stock: 4 },
  { value: "northwest-seattle", label: "NorthWest Motors Seattle", stock: 12 },
  { value: "northwest-portland", label: "NorthWest Motors Portland", stock: 2 },
  { value: "northwest-sanfrancisco", label: "NorthWest Motors San Francisco", stock: 1 },
  { value: "northwest-losangeles", label: "NorthWest Motors Los Angeles", stock: 5 },
  { value: "premium-auto", label: "Premium Auto Group", stock: 3 },
  { value: "luxury-motors", label: "Luxury Motors", stock: 6 },
  { value: "city-cars", label: "City Cars", stock: 8 },
]

export const odometerOptions = [
  { value: "0", label: "0 Km" },
  { value: "1000", label: "1,000 Km" },
  { value: "5000", label: "$5,000 Km" },
  { value: "10000", label: "10,000 Km" },
  { value: "20000", label: "20,000 Km" },
  { value: "30000", label: "30,000 Km" },
  { value: "40000", label: "40,000 Km" },
  { value: "50000", label: "50,000 Km" },
  { value: "60000", label: "60,000 Km" },
  { value: "70000", label: "70,000 Km" },
  { value: "80000", label: "80,000 Km" },
  { value: "90000", label: "90,000 Km" },
  { value: "100000", label: "100,000 Km" },
  { value: "150000", label: "150,000 Km" },
  { value: "200000", label: "200,000 Km" },
  { value: "250000", label: "250,000 Km" },
  { value: "300000", label: "300,000 Km" },
  { value: "500000", label: "500,000 Km" },
  { value: "750000", label: "750,000 Km" },
  { value: "1000000", label: "1,000,000 Km" },
]

export const transmissionOptions = [
  { value: "automatic", label: "Automatic" },
  { value: "manual", label: "Manual" },
  { value: "continually-variable", label: "Continually variable" },
  { value: "dual-clutch", label: "Dual clutch" },
  { value: "sequential-manual", label: "Sequential manual" },
  { value: "semi-automatic", label: "Semi automatic" }
];

export const fuelOptions = [
  { value: "petrol", label: "Petrol" },
  { value: "diesel", label: "Diesel" },
  { value: "hybrid", label: "Hybrid" },
  { value: "electric", label: "Electric" }
];

// Cylinder options
export const cylinderOptions = [
  { value: "3", label: "3 Cylinder", stock: 12 },
  { value: "4", label: "4 Cylinder", stock: 87 },
  { value: "6", label: "6 Cylinder", stock: 45 },
  { value: "8", label: "8 Cylinder", stock: 23 },
  { value: "10", label: "10 Cylinder", stock: 5 },
  { value: "12", label: "12 Cylinder", stock: 3 },
]

// Engine Size options
export const engineSizeOptions = [
  { value: "1000", label: "1.0 L", stock: 8 },
  { value: "1200", label: "1.2 L", stock: 12 },
  { value: "1500", label: "1.5 L", stock: 18 },
  { value: "1600", label: "1.6 L", stock: 24 },
  { value: "1800", label: "1.8 L", stock: 32 },
  { value: "2000", label: "2.0 L", stock: 45 },
  { value: "2500", label: "2.5 L", stock: 38 },
  { value: "3000", label: "3.0 L", stock: 29 },
  { value: "3500", label: "3.5 L", stock: 22 },
  { value: "4000", label: "4.0 L", stock: 15 },
  { value: "5000", label: "5.0 L", stock: 9 },
  { value: "6000", label: "6.0 L+", stock: 5 },
]

// Fuel Economy options
export const fuelEconomyOptions = [
  { value: "4", label: "4L/100km or less", stock: 15 },
  { value: "5", label: "5L/100km or less", stock: 28 },
  { value: "6", label: "6L/100km or less", stock: 42 },
  { value: "7", label: "7L/100km or less", stock: 56 },
  { value: "8", label: "8L/100km or less", stock: 68 },
  { value: "9", label: "9L/100km or less", stock: 75 },
  { value: "10", label: "10L/100km or less", stock: 82 },
  { value: "12", label: "12L/100km or less", stock: 95 },
]

// Tow capacity options
export const towOptions = [
  { value: "750", label: "750 kg" },
  { value: "1500", label: "1,500 kg" },
  { value: "2000", label: "2,000 kg" },
  { value: "2500", label: "2,500 kg" },
  { value: "3000", label: "3,000 kg" },
  { value: "3500", label: "3,500 kg" },
  { value: "3750", label: "3,750 kg" },
]

// Torque options
export const torqueOptions = [
  { value: "200", label: "200 Nm" },
  { value: "400", label: "400 Nm" },
  { value: "600", label: "600 Nm" },
  { value: "800", label: "800 Nm" },
  { value: "1000", label: "1,000 Nm" },
]

// Doors options
export const doorsOptions = [
  { value: "2", label: "2 Doors", stock: 18 },
  { value: "3", label: "3 Doors", stock: 12 },
  { value: "4", label: "4 Doors", stock: 95 },
  { value: "5", label: "5 Doors", stock: 85 },
]

// Seats options
export const seatsOptions = [
  { value: "2", label: "2 Seats", stock: 8 },
  { value: "4", label: "4 Seats", stock: 25 },
  { value: "5", label: "5 Seats", stock: 105 },
  { value: "6", label: "6 Seats", stock: 15 },
  { value: "7", label: "7 Seats", stock: 28 },
  { value: "8", label: "8+ Seats", stock: 12 },
]

// Lifestyle options
export const lifestyleOptions = [
  { value: "family", label: "Family", stock: 68 },
  { value: "tradie", label: "Tradie", stock: 45 },
  { value: "green", label: "Green", stock: 32 },
  { value: "performance", label: "Performance", stock: 28 },
  { value: "midsize-cruisers", label: "Midsize Cruisers", stock: 22 },
]

// Colour options
export const colourOptions = [
  { value: "black", label: "Black", stock: 48 },
  { value: "white", label: "White", stock: 52 },
  { value: "silver", label: "Silver", stock: 38 },
  { value: "grey", label: "Grey", stock: 35 },
  { value: "blue", label: "Blue", stock: 28 },
  { value: "red", label: "Red", stock: 22 },
  { value: "green", label: "Green", stock: 12 },
  { value: "yellow", label: "Yellow", stock: 5 },
  { value: "orange", label: "Orange", stock: 4 },
  { value: "brown", label: "Brown", stock: 8 },
  { value: "purple", label: "Purple", stock: 2 },
  { value: "gold", label: "Gold", stock: 3 },
]


// Sample vehicle data
export const vehicles: Vehicle[] = [
  {
    id: 1,
    make: "Suzuki",
    model: "Jimny",
    year: 2025,
    trim: "XC",
    km: 20178,
    transmission: "Automatic",
    location: "NorthWest Motors Seattle WA",
    fuel: "Petrol",
    price: 36450,
    weeklyPayment: 178.28,
    comparisonRate: 10,
    image: "/car1.jpg",
  },
  {
    id: 2,
    make: "Suzuki",
    model: "Jimny",
    year: 2025,
    trim: "XC",
    km: 16,
    transmission: "Automatic",
    location: "NorthWest Motors Seattle WA",
    fuel: "Petrol",
    price: 39950,
    weeklyPayment: 195.4,
    comparisonRate: 10,
    image: "/car2.jpg",
  },
  {
    id: 3,
    make: "Suzuki",
    model: "Jimny",
    year: 2025,
    trim: "XC",
    km: 14,
    transmission: "Automatic",
    location: "NorthWest Motors Seattle WA",
    fuel: "Petrol",
    price: 36990,
    weeklyPayment: 180.92,
    comparisonRate: 10,
    image: "/car3.jpg",
  },
  {
    id: 4,
    make: "Toyota",
    model: "RAV4",
    year: 2023,
    trim: "GX",
    km: 8500,
    transmission: "Automatic",
    location: "NorthWest Motors Portland OR",
    fuel: "Hybrid",
    price: 42500,
    weeklyPayment: 207.82,
    comparisonRate: 10,
    image: "/car4.jpg",
  },
  {
    id: 5,
    make: "Honda",
    model: "CR-V",
    year: 2023,
    trim: "VTi-L",
    km: 12000,
    transmission: "Automatic",
    location: "NorthWest Motors San Francisco CA",
    fuel: "Petrol",
    price: 39800,
    weeklyPayment: 194.67,
    comparisonRate: 10,
    image: "/car5.jpg",
  },
  {
    id: 6,
    make: "Ford",
    model: "Mustang",
    year: 2022,
    trim: "GT",
    km: 8000,
    transmission: "Manual",
    location: "NorthWest Motors Los Angeles CA",
    fuel: "Petrol",
    price: 56700,
    weeklyPayment: 277.25,
    comparisonRate: 10,
    image: "/car-placeholder.png",
  },
  {
    id: 7,
    make: "BMW",
    model: "X5",
    year: 2023,
    trim: "xDrive40i",
    km: 5200,
    transmission: "Automatic",
    location: "NorthWest Motors Seattle WA",
    fuel: "Petrol",
    price: 89500,
    weeklyPayment: 437.65,
    comparisonRate: 10,
    image: "/car-placeholder.png",
  },
  {
    id: 8,
    make: "Mercedes-Benz",
    model: "GLC",
    year: 2024,
    trim: "300",
    km: 3500,
    transmission: "Automatic",
    location: "NorthWest Motors Portland OR",
    fuel: "Petrol",
    price: 76800,
    weeklyPayment: 375.68,
    comparisonRate: 10,
    image: "/car-placeholder.png",
  },
  {
    id: 9,
    make: "Audi",
    model: "Q5",
    year: 2023,
    trim: "45 TFSI",
    km: 7800,
    transmission: "Automatic",
    location: "NorthWest Motors San Francisco CA",
    fuel: "Petrol",
    price: 68900,
    weeklyPayment: 337.05,
    comparisonRate: 10,
    image: "/car-placeholder.png",
  },
  {
    id: 10,
    make: "Tesla",
    model: "Model 3",
    year: 2024,
    trim: "Long Range",
    km: 2100,
    transmission: "Automatic",
    location: "NorthWest Motors Seattle WA",
    fuel: "Electric",
    price: 62400,
    weeklyPayment: 305.25,
    comparisonRate: 10,
    image: "/car-placeholder.png",
  },
  {
    id: 11,
    make: "Lexus",
    model: "RX",
    year: 2023,
    trim: "350",
    km: 9200,
    transmission: "Automatic",
    location: "NorthWest Motors Portland OR",
    fuel: "Hybrid",
    price: 72500,
    weeklyPayment: 354.65,
    comparisonRate: 10,
    image: "/car-placeholder.png",
  },
  {
    id: 12,
    make: "Porsche",
    model: "Macan",
    year: 2022,
    trim: "S",
    km: 15000,
    transmission: "Automatic",
    location: "NorthWest Motors Los Angeles CA",
    fuel: "Petrol",
    price: 84900,
    weeklyPayment: 415.25,
    comparisonRate: 10,
    image: "/car-placeholder.png",
  },
  {
    id: 13,
    make: "Volvo",
    model: "XC60",
    year: 2023,
    trim: "T6",
    km: 8700,
    transmission: "Automatic",
    location: "NorthWest Motors San Francisco CA",
    fuel: "Petrol",
    price: 65800,
    weeklyPayment: 321.85,
    comparisonRate: 10,
    image: "/car-placeholder.png",
  },
  {
    id: 14,
    make: "Land Rover",
    model: "Range Rover Sport",
    year: 2022,
    trim: "HSE",
    km: 18500,
    transmission: "Automatic",
    location: "NorthWest Motors Seattle WA",
    fuel: "Petrol",
    price: 92500,
    weeklyPayment: 452.45,
    comparisonRate: 10,
    image: "/car-placeholder.png",
  },
  {
    id: 15,
    make: "Jeep",
    model: "Grand Cherokee",
    year: 2023,
    trim: "Limited",
    km: 10200,
    transmission: "Automatic",
    location: "NorthWest Motors Portland OR",
    fuel: "Petrol",
    price: 58900,
    weeklyPayment: 288.15,
    comparisonRate: 10,
    image: "/car-placeholder.png",
  },
  {
    id: 16,
    make: "Mazda",
    model: "CX-5",
    year: 2024,
    trim: "GT",
    km: 4500,
    transmission: "Automatic",
    location: "NorthWest Motors San Francisco CA",
    fuel: "Petrol",
    price: 42900,
    weeklyPayment: 209.85,
    comparisonRate: 10,
    image: "/car-placeholder.png",
  },
  {
    id: 17,
    make: "Subaru",
    model: "Outback",
    year: 2023,
    trim: "Premium",
    km: 9800,
    transmission: "Automatic",
    location: "NorthWest Motors Los Angeles CA",
    fuel: "Petrol",
    price: 39500,
    weeklyPayment: 193.15,
    comparisonRate: 10,
    image: "/car-placeholder.png",
  },
  {
    id: 18,
    make: "Volkswagen",
    model: "Tiguan",
    year: 2023,
    trim: "SEL",
    km: 7200,
    transmission: "Automatic",
    location: "NorthWest Motors Seattle WA",
    fuel: "Petrol",
    price: 41800,
    weeklyPayment: 204.45,
    comparisonRate: 10,
    image: "/car-placeholder.png",
  },
  {
    id: 19,
    make: "Hyundai",
    model: "Santa Fe",
    year: 2024,
    trim: "Limited",
    km: 3200,
    transmission: "Automatic",
    location: "NorthWest Motors Portland OR",
    fuel: "Hybrid",
    price: 45900,
    weeklyPayment: 224.55,
    comparisonRate: 10,
    image: "/car-placeholder.png",
  },
  {
    id: 20,
    make: "Kia",
    model: "Sorento",
    year: 2023,
    trim: "SX",
    km: 8900,
    transmission: "Automatic",
    location: "NorthWest Motors San Francisco CA",
    fuel: "Petrol",
    price: 43500,
    weeklyPayment: 212.75,
    comparisonRate: 10,
    image: "/car-placeholder.png",
  },
]