export const makeOptions = [
    { value: "alfa-romeo", label: "ALFA ROMEO", stock: 1 },
    { value: "aston-martin", label: "ASTON MARTIN", stock: 1 },
    { value: "audi", label: "AUDI", stock: 44 },
    { value: "bmw", label: "BMW", stock: 72 },
    { value: "chevrolet", label: "CHEVROLET", stock: 7 },
    { value: "daihatsu", label: "DAIHATSU", stock: 1 },
    { value: "ford", label: "FORD", stock: 9 },
    { value: "honda", label: "HONDA", stock: 18 },
    { value: "toyota", label: "TOYOTA", stock: 24 },
    { value: "nissan", label: "NISSAN", stock: 9 },
    { value: "mercedes", label: "MERCEDES", stock: 5 },
  ]
  
export  const modelOptions = [
    { value: "camry", label: "CAMRY", stock: 8 },
    { value: "corolla", label: "COROLLA", stock: 6 },
    { value: "civic", label: "CIVIC", stock: 7 },
    { value: "accord", label: "ACCORD", stock: 5 },
    { value: "f150", label: "F-150", stock: 9 },
    { value: "silverado", label: "SILVERADO", stock: 6 },
    { value: "altima", label: "ALTIMA", stock: 4 },
  ]
  
export  const locationOptions = [
    { value: "seattle", label: "SEATTLE, WA", stock: 42 },
    { value: "portland", label: "PORTLAND, OR", stock: 35 },
    { value: "spokane", label: "SPOKANE, WA", stock: 18 },
    { value: "boise", label: "BOISE, ID", stock: 15 },
    { value: "vancouver", label: "VANCOUVER, WA", stock: 12 },
  ]

  


// Sample vehicle data
export const vehicles = [
  {
    id: 1,
    make: "Suzuki",
    model: "Jimny",
    year: 2025,
    trim: "XC",
    km: 20178,
    transmission: "Automatic",
    location: "NorthWest Motors Seattle WA",
    fuel: "Petrol",
    price: 36450,
    weeklyPayment: 178.28,
    comparisonRate: 10,
    image: "/suzuki-jimny-offroad.png",
  },
  {
    id: 2,
    make: "Suzuki",
    model: "Jimny",
    year: 2025,
    trim: "XC",
    km: 16,
    transmission: "Automatic",
    location: "NorthWest Motors Seattle WA",
    fuel: "Petrol",
    price: 39950,
    weeklyPayment: 195.4,
    comparisonRate: 10,
    image: "/suzuki-jimny-offroad.png",
  },
  {
    id: 3,
    make: "Suzuki",
    model: "Jimny",
    year: 2025,
    trim: "XC",
    km: 14,
    transmission: "Automatic",
    location: "NorthWest Motors Seattle WA",
    fuel: "Petrol",
    price: 36990,
    weeklyPayment: 180.92,
    comparisonRate: 10,
    image: "/suzuki-jimny-offroad.png",
  },
  {
    id: 4,
    make: "Toyota",
    model: "RAV4",
    year: 2023,
    trim: "GX",
    km: 8500,
    transmission: "Automatic",
    location: "NorthWest Motors Portland OR",
    fuel: "Hybrid",
    price: 42500,
    weeklyPayment: 207.82,
    comparisonRate: 10,
    image: "/suzuki-jimny-offroad.png",
  },
  {
    id: 5,
    make: "Honda",
    model: "CR-V",
    year: 2023,
    trim: "VTi-L",
    km: 12000,
    transmission: "Automatic",
    location: "NorthWest Motors San Francisco CA",
    fuel: "Petrol",
    price: 39800,
    weeklyPayment: 194.67,
    comparisonRate: 10,
    image: "/suzuki-jimny-offroad.png",
  },
  {
    id: 6,
    make: "Ford",
    model: "Mustang",
    year: 2022,
    trim: "GT",
    km: 8000,
    transmission: "Manual",
    location: "NorthWest Motors Los Angeles CA",
    fuel: "Petrol",
    price: 56700,
    weeklyPayment: 277.25,
    comparisonRate: 10,
    image: "/suzuki-jimny-offroad.png",
  },
  {
    id: 7,
    make: "BMW",
    model: "X5",
    year: 2023,
    trim: "xDrive40i",
    km: 5200,
    transmission: "Automatic",
    location: "NorthWest Motors Seattle WA",
    fuel: "Petrol",
    price: 89500,
    weeklyPayment: 437.65,
    comparisonRate: 10,
    image: "/suzuki-jimny-offroad.png",
  },
  {
    id: 8,
    make: "Mercedes-Benz",
    model: "GLC",
    year: 2024,
    trim: "300",
    km: 3500,
    transmission: "Automatic",
    location: "NorthWest Motors Portland OR",
    fuel: "Petrol",
    price: 76800,
    weeklyPayment: 375.68,
    comparisonRate: 10,
    image: "/suzuki-jimny-offroad.png",
  },
  {
    id: 9,
    make: "Audi",
    model: "Q5",
    year: 2023,
    trim: "45 TFSI",
    km: 7800,
    transmission: "Automatic",
    location: "NorthWest Motors San Francisco CA",
    fuel: "Petrol",
    price: 68900,
    weeklyPayment: 337.05,
    comparisonRate: 10,
    image: "/suzuki-jimny-offroad.png",
  },
  {
    id: 10,
    make: "Tesla",
    model: "Model 3",
    year: 2024,
    trim: "Long Range",
    km: 2100,
    transmission: "Automatic",
    location: "NorthWest Motors Seattle WA",
    fuel: "Electric",
    price: 62400,
    weeklyPayment: 305.25,
    comparisonRate: 10,
    image: "/suzuki-jimny-offroad.png",
  },
  {
    id: 11,
    make: "Lexus",
    model: "RX",
    year: 2023,
    trim: "350",
    km: 9200,
    transmission: "Automatic",
    location: "NorthWest Motors Portland OR",
    fuel: "Hybrid",
    price: 72500,
    weeklyPayment: 354.65,
    comparisonRate: 10,
    image: "/suzuki-jimny-offroad.png",
  },
  {
    id: 12,
    make: "Porsche",
    model: "Macan",
    year: 2022,
    trim: "S",
    km: 15000,
    transmission: "Automatic",
    location: "NorthWest Motors Los Angeles CA",
    fuel: "Petrol",
    price: 84900,
    weeklyPayment: 415.25,
    comparisonRate: 10,
    image: "/suzuki-jimny-offroad.png",
  },
  {
    id: 13,
    make: "Volvo",
    model: "XC60",
    year: 2023,
    trim: "T6",
    km: 8700,
    transmission: "Automatic",
    location: "NorthWest Motors San Francisco CA",
    fuel: "Petrol",
    price: 65800,
    weeklyPayment: 321.85,
    comparisonRate: 10,
    image: "/suzuki-jimny-offroad.png",
  },
  {
    id: 14,
    make: "Land Rover",
    model: "Range Rover Sport",
    year: 2022,
    trim: "HSE",
    km: 18500,
    transmission: "Automatic",
    location: "NorthWest Motors Seattle WA",
    fuel: "Petrol",
    price: 92500,
    weeklyPayment: 452.45,
    comparisonRate: 10,
    image: "/suzuki-jimny-offroad.png",
  },
  {
    id: 15,
    make: "Jeep",
    model: "Grand Cherokee",
    year: 2023,
    trim: "Limited",
    km: 10200,
    transmission: "Automatic",
    location: "NorthWest Motors Portland OR",
    fuel: "Petrol",
    price: 58900,
    weeklyPayment: 288.15,
    comparisonRate: 10,
    image: "/suzuki-jimny-offroad.png",
  },
  {
    id: 16,
    make: "Mazda",
    model: "CX-5",
    year: 2024,
    trim: "GT",
    km: 4500,
    transmission: "Automatic",
    location: "NorthWest Motors San Francisco CA",
    fuel: "Petrol",
    price: 42900,
    weeklyPayment: 209.85,
    comparisonRate: 10,
    image: "/suzuki-jimny-offroad.png",
  },
  {
    id: 17,
    make: "Subaru",
    model: "Outback",
    year: 2023,
    trim: "Premium",
    km: 9800,
    transmission: "Automatic",
    location: "NorthWest Motors Los Angeles CA",
    fuel: "Petrol",
    price: 39500,
    weeklyPayment: 193.15,
    comparisonRate: 10,
    image: "/suzuki-jimny-offroad.png",
  },
  {
    id: 18,
    make: "Volkswagen",
    model: "Tiguan",
    year: 2023,
    trim: "SEL",
    km: 7200,
    transmission: "Automatic",
    location: "NorthWest Motors Seattle WA",
    fuel: "Petrol",
    price: 41800,
    weeklyPayment: 204.45,
    comparisonRate: 10,
    image: "/suzuki-jimny-offroad.png",
  },
  {
    id: 19,
    make: "Hyundai",
    model: "Santa Fe",
    year: 2024,
    trim: "Limited",
    km: 3200,
    transmission: "Automatic",
    location: "NorthWest Motors Portland OR",
    fuel: "Hybrid",
    price: 45900,
    weeklyPayment: 224.55,
    comparisonRate: 10,
    image: "/suzuki-jimny-offroad.png",
  },
  {
    id: 20,
    make: "Kia",
    model: "Sorento",
    year: 2023,
    trim: "SX",
    km: 8900,
    transmission: "Automatic",
    location: "NorthWest Motors San Francisco CA",
    fuel: "Petrol",
    price: 43500,
    weeklyPayment: 212.75,
    comparisonRate: 10,
    image: "/suzuki-jimny-offroad.png",
  },
]